[2025-08-22T04:06:32.386+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T04:06:32.439+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_offshore_data manual__2025-08-22T04:01:37+00:00 [queued]>
[2025-08-22T04:06:32.460+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_offshore_data manual__2025-08-22T04:01:37+00:00 [queued]>
[2025-08-22T04:06:32.461+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2025-08-22T04:06:32.525+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load_offshore_data> on 2025-08-22 04:01:37+00:00
[2025-08-22T04:06:32.568+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=842) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-22T04:06:32.579+0000] {standard_task_runner.py:72} INFO - Started process 847 to run task
[2025-08-22T04:06:32.584+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_stg', 'load_offshore_data', 'manual__2025-08-22T04:01:37+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_stg.py', '--cfg-path', '/tmp/tmp89o7ujde']
[2025-08-22T04:06:32.593+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask load_offshore_data
[2025-08-22T04:06:32.794+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_stg.load_offshore_data manual__2025-08-22T04:01:37+00:00 [running]> on host 21c40e4c1785
[2025-08-22T04:06:33.845+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_stg' AIRFLOW_CTX_TASK_ID='load_offshore_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T04:01:37+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T04:01:37+00:00'
[2025-08-22T04:06:33.848+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T04:06:34.770+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T04:06:35.314+0000] {logging_mixin.py:190} INFO - Data loaded to stg.stg_drill_ships successfully.
[2025-08-22T04:06:35.351+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T04:06:35.458+0000] {logging_mixin.py:190} INFO - Data loaded to stg.stg_offshore_plant_equipment_master successfully.
[2025-08-22T04:06:35.464+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-08-22T04:06:35.503+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T04:06:35.503+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_stg, task_id=load_offshore_data, run_id=manual__2025-08-22T04:01:37+00:00, execution_date=20250822T040137, start_date=20250822T040632, end_date=20250822T040635
[2025-08-22T04:06:35.636+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-08-22T04:06:35.774+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T04:06:35.780+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
