[2025-08-22T05:47:10.967+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T05:47:10.984+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_stg.create_and_load_data_to_stg manual__2025-08-22T05:47:07+00:00 [queued]>
[2025-08-22T05:47:10.992+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_stg.create_and_load_data_to_stg manual__2025-08-22T05:47:07+00:00 [queued]>
[2025-08-22T05:47:10.993+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-08-22T05:47:11.005+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): create_and_load_data_to_stg> on 2025-08-22 05:47:07+00:00
[2025-08-22T05:47:11.015+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-22T05:47:11.017+0000] {standard_task_runner.py:72} INFO - Started process 2220 to run task
[2025-08-22T05:47:11.018+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_stg', 'create_and_load_data_to_stg', 'manual__2025-08-22T05:47:07+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_stg.py', '--cfg-path', '/tmp/tmp04mipeop']
[2025-08-22T05:47:11.021+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask create_and_load_data_to_stg
[2025-08-22T05:47:11.066+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_stg.create_and_load_data_to_stg manual__2025-08-22T05:47:07+00:00 [running]> on host 21c40e4c1785
[2025-08-22T05:47:11.361+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_stg' AIRFLOW_CTX_TASK_ID='create_and_load_data_to_stg' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T05:47:07+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T05:47:07+00:00'
[2025-08-22T05:47:11.362+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T05:47:11.405+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T05:47:11.490+0000] {logging_mixin.py:190} INFO - Data loaded to STG schema for 해양플랜트 in table '해양플랜트_stg' successfully.
[2025-08-22T05:47:11.539+0000] {logging_mixin.py:190} INFO - Data loaded to STG schema for 특수선 in table '특수선_stg' successfully.
[2025-08-22T05:47:11.589+0000] {logging_mixin.py:190} INFO - Data loaded to STG schema for 상선 in table '상선_stg' successfully.
[2025-08-22T05:47:11.590+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-08-22T05:47:11.599+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T05:47:11.600+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_stg, task_id=create_and_load_data_to_stg, run_id=manual__2025-08-22T05:47:07+00:00, execution_date=20250822T054707, start_date=20250822T054710, end_date=20250822T054711
[2025-08-22T05:47:11.633+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-08-22T05:47:11.651+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T05:47:11.652+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
