[2025-08-22T05:06:22.080+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T05:06:22.117+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_special_data manual__2025-08-22T05:06:17+00:00 [queued]>
[2025-08-22T05:06:22.137+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_special_data manual__2025-08-22T05:06:17+00:00 [queued]>
[2025-08-22T05:06:22.138+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-08-22T05:06:22.204+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load_special_data> on 2025-08-22 05:06:17+00:00
[2025-08-22T05:06:22.230+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1653) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-22T05:06:22.234+0000] {standard_task_runner.py:72} INFO - Started process 1661 to run task
[2025-08-22T05:06:22.235+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_stg', 'load_special_data', 'manual__2025-08-22T05:06:17+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_stg.py', '--cfg-path', '/tmp/tmp3u6npsdx']
[2025-08-22T05:06:22.240+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask load_special_data
[2025-08-22T05:06:22.382+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_stg.load_special_data manual__2025-08-22T05:06:17+00:00 [running]> on host 21c40e4c1785
[2025-08-22T05:06:22.614+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_stg' AIRFLOW_CTX_TASK_ID='load_special_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T05:06:17+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T05:06:17+00:00'
[2025-08-22T05:06:22.615+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T05:06:22.667+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T05:06:22.775+0000] {logging_mixin.py:190} INFO - Data for 'Submarine' loaded to table 'stg_submarines' in STG schema successfully.
[2025-08-22T05:06:22.776+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-08-22T05:06:22.794+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T05:06:22.795+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_stg, task_id=load_special_data, run_id=manual__2025-08-22T05:06:17+00:00, execution_date=20250822T050617, start_date=20250822T050622, end_date=20250822T050622
[2025-08-22T05:06:22.858+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-08-22T05:06:22.889+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T05:06:22.891+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
